services:
  db:
    image: postgres:15
    container_name: wallet_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wallet"]
      interval: 2s
      timeout: 2s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/wallet
    networks:
      - app-network
    command: >
      sh -c "alembic upgrade head && 
      uvicorn src.main:app --host 0.0.0.0 --port 8000"

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge