FROM python:3.12.8-slim

WORKDIR /app

COPY . .

RUN pip install poetry
RUN poetry install --no-root --without dev

ENV PYTHONPATH=/app/src

CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]