# Используем тот же базовый образ Python
FROM python:3.12.8-slim

# Указываем рабочую директорию
WORKDIR /app

# Копируем все файлы в контейнер
COPY . .

# Устанавливаем Poetry и зависимости
RUN pip install poetry
RUN poetry install --no-root

# Устанавливаем pytest для тестов
RUN poetry add --dev pytest pytest-asyncio

# Указываем, что нужно запустить тесты
CMD ["poetry", "run", "pytest"]
